### ISSUE TITLE
After more than one pressings on 'Identify' button the results cannot be cleaned with 'Remove' button

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#116] opened 2021-05-05 10:21 UTC
The 'Identify' can be clicked more than one times and each time creates its own lay of results as separated set of blue rectangles. 
Only the first of them can be cleaned from page via 'Remove' button but all other layers will stay.
The trying of pressing on 'Remove' to clean other returns an error at Console:
```
Error handling response: TypeError: Cannot read property 'remove' of null
    at <anonymous>:4:41
    at Array.forEach (<anonymous>)
    at f (<anonymous>:3:17)
``` 

**To discuss:** should we forbid the second pressing on 'Identify' before cleaning of the results of the first? or to find another solution?

**Comment by AlexeyGirin** [comment] 2021-05-05 13:36
Duplicate of #115

**Closed by AlexeyGirin** 2021-05-05 13:36 UTC
